#!/usr/bin/env groovy
@Library('defra-shared@master') _

pipeline {
    agent any
    parameters {
        booleanParam(name: 'REBUILD_IMAGE', defaultValue: false, description: 'Force the performance test image to be rebuilt?')
    }
    stages {
        stage('Building test container') {
            steps {
                script {
                    dir('performance/frontend') {
                        ansiColor('xterm') {
                            def buildArgs = " ."
                            if (params.REBUILD_IMAGE) {
                                buildArgs = '--no-cache ' + buildArgs
                            }
                            def image = docker.build("defra/rod-catch-returns-performance-tests", buildArgs)

                            // sh "mkdir -p ${WORKSPACE}/results"
                            // image.run(
                            //     "--rm " +
                            //     "-v ${WORKSPACE}:/tests"

                            // )
                        }
                    }
                }
            }
        }
        stage('Executing tests') {
            steps {
                script {
                    dir('performance/frontend') {
                        ansiColor('xterm') {
                            def mounts = [ "type=bind,source=${WORKSPACE}/tests,target=/app/tests"]
                            def cwd = pwd()
                            sh "mkdir -p ${cwd}/results"
                            dockerRun('defra/rod-catch-returns-performance-tests', null, [], "-v '${cwd}:/tests'")
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts allowEmptyArchive: true, artifacts: 'results/**'
        }
        cleanup {
            cleanWs cleanWhenFailure: true
        }
    }
}
